build:
    tests:
        override:
            -
                command: 'composer install; vendor/bin/phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'clover'
